version: "3.8"

services:
  app:
    build: .
    hostname: app
    restart: unless-stopped
    ports:
      - '8889:8080'
    networks:
      - vm_net

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data/:/tmp/tempo
    ports:
      - "15268:14268" # jaeger ingest
      - "3500:3200" # tempo
      - "4517:4317" # otlp grpc
      - "4518:4318" # otlp http
      - "9511:9411" # zipkin
    # network_mode: "host"
    healthcheck:
      test: [ "CMD", "grpc", "health", "check" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vm_net

  prometheus:
    image: prom/prometheus
    ports:
      - "9590:9090"
    volumes:
      - ./prometheus:/etc/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - vm_net

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3500:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki-config.yaml
    command: -config.file=/etc/loki-config.yaml
    networks:
      - vm_net

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail-config.yaml
      - ./var/log:/var/log
    command: -config.file=/etc/promtail-config.yaml
    networks:
      - vm_net

  vmagent:
    image: victoriametrics/vmagent:v1.94.0
    depends_on:
      - "victoriametrics"
    ports:
      - "8529:8429"
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - vm_net
    restart: always

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.94.0
    ports:
      - "8528:8428"
      - "8589:8089"
      - "2503:2003"
      - "4542:4242"
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    networks:
      - vm_net
    restart: always

  grafana:
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - "3500:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
    networks:
      - vm_net
    restart: always

volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}
  tempodata: {}

networks:
  vm_net:
