# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PurchaseResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, order_id: int=None):  # noqa: E501
        """PurchaseResponse - a model defined in Swagger

        :param message: The message of this PurchaseResponse.  # noqa: E501
        :type message: str
        :param order_id: The order_id of this PurchaseResponse.  # noqa: E501
        :type order_id: int
        """
        self.swagger_types = {
            'message': str,
            'order_id': int
        }

        self.attribute_map = {
            'message': 'message',
            'order_id': 'orderId'
        }
        self._message = message
        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'PurchaseResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PurchaseResponse of this PurchaseResponse.  # noqa: E501
        :rtype: PurchaseResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this PurchaseResponse.

        Purchase message  # noqa: E501

        :return: The message of this PurchaseResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this PurchaseResponse.

        Purchase message  # noqa: E501

        :param message: The message of this PurchaseResponse.
        :type message: str
        """

        self._message = message

    @property
    def order_id(self) -> int:
        """Gets the order_id of this PurchaseResponse.

        Unique identifier of the order  # noqa: E501

        :return: The order_id of this PurchaseResponse.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this PurchaseResponse.

        Unique identifier of the order  # noqa: E501

        :param order_id: The order_id of this PurchaseResponse.
        :type order_id: int
        """

        self._order_id = order_id
