# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_registration_address import UserRegistrationAddress  # noqa: F401,E501
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, username: str=None, email: str=None, address: UserRegistrationAddress=None):  # noqa: E501
        """User - a model defined in Swagger

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param address: The address of this User.  # noqa: E501
        :type address: UserRegistrationAddress
        """
        self.swagger_types = {
            'id': int,
            'username': str,
            'email': str,
            'address': UserRegistrationAddress
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'email': 'email',
            'address': 'address'
        }
        self._id = id
        self._username = username
        self._email = email
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.

        Unique identifier of the user  # noqa: E501

        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.

        Unique identifier of the user  # noqa: E501

        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def username(self) -> str:
        """Gets the username of this User.

        Username of the user  # noqa: E501

        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this User.

        Username of the user  # noqa: E501

        :param username: The username of this User.
        :type username: str
        """

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this User.

        Email address of the user  # noqa: E501

        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.

        Email address of the user  # noqa: E501

        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def address(self) -> UserRegistrationAddress:
        """Gets the address of this User.


        :return: The address of this User.
        :rtype: UserRegistrationAddress
        """
        return self._address

    @address.setter
    def address(self, address: UserRegistrationAddress):
        """Sets the address of this User.


        :param address: The address of this User.
        :type address: UserRegistrationAddress
        """

        self._address = address
