# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserRegistrationAddress(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, street: str=None, city: str=None, state: str=None, zip: str=None):  # noqa: E501
        """UserRegistrationAddress - a model defined in Swagger

        :param street: The street of this UserRegistrationAddress.  # noqa: E501
        :type street: str
        :param city: The city of this UserRegistrationAddress.  # noqa: E501
        :type city: str
        :param state: The state of this UserRegistrationAddress.  # noqa: E501
        :type state: str
        :param zip: The zip of this UserRegistrationAddress.  # noqa: E501
        :type zip: str
        """
        self.swagger_types = {
            'street': str,
            'city': str,
            'state': str,
            'zip': str
        }

        self.attribute_map = {
            'street': 'street',
            'city': 'city',
            'state': 'state',
            'zip': 'zip'
        }
        self._street = street
        self._city = city
        self._state = state
        self._zip = zip

    @classmethod
    def from_dict(cls, dikt) -> 'UserRegistrationAddress':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserRegistration_address of this UserRegistrationAddress.  # noqa: E501
        :rtype: UserRegistrationAddress
        """
        return util.deserialize_model(dikt, cls)

    @property
    def street(self) -> str:
        """Gets the street of this UserRegistrationAddress.

        Street  # noqa: E501

        :return: The street of this UserRegistrationAddress.
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street: str):
        """Sets the street of this UserRegistrationAddress.

        Street  # noqa: E501

        :param street: The street of this UserRegistrationAddress.
        :type street: str
        """

        self._street = street

    @property
    def city(self) -> str:
        """Gets the city of this UserRegistrationAddress.

        City  # noqa: E501

        :return: The city of this UserRegistrationAddress.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this UserRegistrationAddress.

        City  # noqa: E501

        :param city: The city of this UserRegistrationAddress.
        :type city: str
        """

        self._city = city

    @property
    def state(self) -> str:
        """Gets the state of this UserRegistrationAddress.

        State  # noqa: E501

        :return: The state of this UserRegistrationAddress.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this UserRegistrationAddress.

        State  # noqa: E501

        :param state: The state of this UserRegistrationAddress.
        :type state: str
        """

        self._state = state

    @property
    def zip(self) -> str:
        """Gets the zip of this UserRegistrationAddress.

        Zip code  # noqa: E501

        :return: The zip of this UserRegistrationAddress.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip: str):
        """Sets the zip of this UserRegistrationAddress.

        Zip code  # noqa: E501

        :param zip: The zip of this UserRegistrationAddress.
        :type zip: str
        """

        self._zip = zip
