# coding: utf-8

"""
    Онлайн-магазин комиксов API

    This is an API specification for a comic purchase application. Users can browse, search, and purchase comics through this API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserRegistrationAddress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'street': 'str',
        'city': 'str',
        'state': 'str',
        'zip': 'str'
    }

    attribute_map = {
        'street': 'street',
        'city': 'city',
        'state': 'state',
        'zip': 'zip'
    }

    def __init__(self, street=None, city=None, state=None, zip=None):  # noqa: E501
        """UserRegistrationAddress - a model defined in Swagger"""  # noqa: E501
        self._street = None
        self._city = None
        self._state = None
        self._zip = None
        self.discriminator = None
        if street is not None:
            self.street = street
        if city is not None:
            self.city = city
        if state is not None:
            self.state = state
        if zip is not None:
            self.zip = zip

    @property
    def street(self):
        """Gets the street of this UserRegistrationAddress.  # noqa: E501

        Street  # noqa: E501

        :return: The street of this UserRegistrationAddress.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this UserRegistrationAddress.

        Street  # noqa: E501

        :param street: The street of this UserRegistrationAddress.  # noqa: E501
        :type: str
        """

        self._street = street

    @property
    def city(self):
        """Gets the city of this UserRegistrationAddress.  # noqa: E501

        City  # noqa: E501

        :return: The city of this UserRegistrationAddress.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this UserRegistrationAddress.

        City  # noqa: E501

        :param city: The city of this UserRegistrationAddress.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def state(self):
        """Gets the state of this UserRegistrationAddress.  # noqa: E501

        State  # noqa: E501

        :return: The state of this UserRegistrationAddress.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this UserRegistrationAddress.

        State  # noqa: E501

        :param state: The state of this UserRegistrationAddress.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def zip(self):
        """Gets the zip of this UserRegistrationAddress.  # noqa: E501

        Zip code  # noqa: E501

        :return: The zip of this UserRegistrationAddress.  # noqa: E501
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this UserRegistrationAddress.

        Zip code  # noqa: E501

        :param zip: The zip of this UserRegistrationAddress.  # noqa: E501
        :type: str
        """

        self._zip = zip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserRegistrationAddress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRegistrationAddress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
