# coding: utf-8

"""
    Онлайн-магазин комиксов API

    This is an API specification for a comic purchase application. Users can browse, search, and purchase comics through this API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_post(self):
        """Test case for users_post

        Register a new user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
