# coding: utf-8

"""
    Онлайн-магазин комиксов API

    This is an API specification for a comic purchase application. Users can browse, search, and purchase comics through this API.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.purchase_response import PurchaseResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPurchaseResponse(unittest.TestCase):
    """PurchaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPurchaseResponse(self):
        """Test PurchaseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.purchase_response.PurchaseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
