name: Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: List directory contents
      run: |
        ls -la
        pwd
        
    - name: Build the Docker Compose stack
      run: docker-compose build
      
    - name: Test the application
      run: |
        docker-compose run web pytest
        docker-compose run web flake8
    - name: Test the application
      run: |
        # Install dependencies
        pip install -r requirements.txt
        pip install pytest
        pip install flask_testing
    
        # Run tests
        pytest
    
        # Run Swagger client tests
        python -m unittest tests.test_swagger_client

    - name: Push the Docker images
      if: success() && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker-compose push
