name: Swagger Server and Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-server-and-client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install server dependencies
      run: |
        cd python-flask-server-generated
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus_client
        pip install prometheus_flask_exporter
        
    - name: Run Swagger Server
      run: |
        cd python-flask-server-generated
        python -m swagger_server.__main__ &
        
    - name: Install client dependencies  
      run: |
        cd python-client-generated
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus_client
        pip install prometheus_flask_exporter
        
    - name: Run Client
      run: |
        cd python-client-generated
        python main.py

# name: Swagger Server

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:

#   run-swagger-server:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r server/requirements.txt
#         pip install prometheus_client
#         pip install prometheus_flask_exporter
#     - name: Run Swagger Server
#       run: |
#         cd server
#         python -m swagger_server.__main__
        
#   run-client:
#     needs: run-swagger-server
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r client/requirements.txt
#         pip install prometheus_client
#         pip install prometheus_flask_exporter
#     - name: Run Client
#       run: |
#         cd client
#         python main.py
